name: Pull Request Approval Check

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review, review_requested]

jobs:
  check-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check PR approval
        id: check_approval
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            // Get the latest review from each reviewer
            const latestReviews = {};
            reviews.forEach(review => {
              // Only consider reviews with a state (APPROVED, CHANGES_REQUESTED, COMMENTED)
              if (review.state) {
                latestReviews[review.user.id] = review;
              }
            });
            
            // Check if there's at least one approval and no rejections
            let approvalCount = 0;
            let rejectionCount = 0;
            
            Object.values(latestReviews).forEach(review => {
              if (review.state === 'APPROVED') {
                approvalCount++;
              } else if (review.state === 'CHANGES_REQUESTED') {
                rejectionCount++;
              }
            });
            
            console.log(`Approvals: ${approvalCount}, Rejections: ${rejectionCount}`);
            
            if (rejectionCount > 0) {
              core.setFailed('Changes have been requested. Please address them before merging.');
              return;
            }
            
            if (approvalCount === 0) {
              console.log('No approvals yet. Waiting for review.');
            } else {
              console.log('PR has been approved!');
            }

  build-and-test:
    runs-on: ubuntu-latest
    needs: check-approval
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      # Add your build and test steps here
      - name: Run tests
        run: |
          echo "Running tests..."
          # Replace with your actual test commands
          # For example: npm test, pytest, etc.
