name: Snyk Infrastructure as Code
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk IAC Test
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          # Set the Snyk API endpoint for the US-02 environment
          SNYK_API: https://api.us.snyk.io
        # with: 
        #   command: monitor